// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrstecklo/micropet/services/orders/orders (interfaces: MessagingSystem)
//
// Generated by this command:
//
//	mockgen -destination=orders_mock/messaging_system_mock.go -package=orders_mock github.com/mrstecklo/micropet/services/orders/orders MessagingSystem
//

// Package orders_mock is a generated GoMock package.
package orders_mock

import (
	reflect "reflect"

	orders "github.com/mrstecklo/micropet/services/orders/orders"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagingSystem is a mock of MessagingSystem interface.
type MockMessagingSystem struct {
	ctrl     *gomock.Controller
	recorder *MockMessagingSystemMockRecorder
	isgomock struct{}
}

// MockMessagingSystemMockRecorder is the mock recorder for MockMessagingSystem.
type MockMessagingSystemMockRecorder struct {
	mock *MockMessagingSystem
}

// NewMockMessagingSystem creates a new mock instance.
func NewMockMessagingSystem(ctrl *gomock.Controller) *MockMessagingSystem {
	mock := &MockMessagingSystem{ctrl: ctrl}
	mock.recorder = &MockMessagingSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagingSystem) EXPECT() *MockMessagingSystemMockRecorder {
	return m.recorder
}

// PublishOrderCreated mocks base method.
func (m *MockMessagingSystem) PublishOrderCreated(order orders.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderCreated", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderCreated indicates an expected call of PublishOrderCreated.
func (mr *MockMessagingSystemMockRecorder) PublishOrderCreated(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderCreated", reflect.TypeOf((*MockMessagingSystem)(nil).PublishOrderCreated), order)
}
